// <auto-generated />
using System;
using DarkestDungeon.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DarkestDungeon.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DarkestDungeonDbContext))]
    [Migration("20260907154835_InitialSerSchema")]
    partial class InitialSerSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DarkestDungeon.Domain.Seres.Ser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AcoesPorTurno")
                        .HasColumnType("int");

                    b.Property<decimal>("BonusDeCritico")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Critico")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DanoBaseMaximo")
                        .HasColumnType("int");

                    b.Property<int>("DanoBaseMinimo")
                        .HasColumnType("int");

                    b.Property<decimal>("Esquiva")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("HpAtual")
                        .HasColumnType("int");

                    b.Property<int>("HpMaximo")
                        .HasColumnType("int");

                    b.Property<int>("Movimento")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Precisao")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Protecao")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Tamanho")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Velocidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seres", null, t =>
                        {
                            t.HasCheckConstraint("CK_Seres_DanoBase", "[DanoBaseMinimo] >= 0 AND [DanoBaseMaximo] >= 0 AND [DanoBaseMinimo] <= [DanoBaseMaximo]");

                            t.HasCheckConstraint("CK_Seres_HP", "[HpMaximo] >= 0 AND [HpAtual] >= 0 AND [HpAtual] <= [HpMaximo]");

                            t.HasCheckConstraint("CK_Seres_Nivel", "[Nivel] >= 0 AND [Nivel] <= 6");

                            t.HasCheckConstraint("CK_Seres_Percentuais", "[Critico] >= 0 AND [Critico] <= 100 AND [BonusDeCritico] >= 0 AND [BonusDeCritico] <= 100 AND [Protecao] >= 0 AND [Protecao] <= 100");

                            t.HasCheckConstraint("CK_Seres_Resistencias", "[Resistencias_Atordoamento] >= 0 AND [Resistencias_Atordoamento] <= 100 AND [Resistencias_Sangramento] >= 0 AND [Resistencias_Sangramento] <= 100 AND [Resistencias_Envenenamento] >= 0 AND [Resistencias_Envenenamento] <= 100 AND [Resistencias_Debuff] >= 0 AND [Resistencias_Debuff] <= 100 AND [Resistencias_Movimento] >= 0 AND [Resistencias_Movimento] <= 100");

                            t.HasCheckConstraint("CK_Seres_Tamanho", "[Tamanho] >= 0 AND [Tamanho] <= 4");
                        });
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Seres.Ser", b =>
                {
                    b.OwnsOne("DarkestDungeon.Domain.Seres.Resistencias", "Resistencias", b1 =>
                        {
                            b1.Property<Guid>("SerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Atordoamento")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("Debuff")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("Envenenamento")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("Movimento")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("Sangramento")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.HasKey("SerId");

                            b1.ToTable("Seres");

                            b1.WithOwner()
                                .HasForeignKey("SerId");
                        });

                    b.Navigation("Resistencias")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
