// <auto-generated />
using System;
using DarkestDungeon.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DarkestDungeon.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DarkestDungeonDbContext))]
    partial class DarkestDungeonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DarkestDungeon.Domain.Classes.Classe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClasseDeHeroi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("ClasseDeHeroi")
                        .IsUnique();

                    b.ToTable("Classes", (string)null);
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Classes.ClasseHabilidade", b =>
                {
                    b.Property<Guid>("ClasseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HabilidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClasseId", "HabilidadeId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("ClassesHabilidades", (string)null);
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Cobertura.EntradaDoMapaDeCobertura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ChaveDoAtributo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notas")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Classe", "Categoria", "ChaveDoAtributo")
                        .IsUnique();

                    b.ToTable("MapaDeCobertura", (string)null);
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Habilidades.Habilidade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Discriminador")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("NomeExibicao")
                        .IsUnique();

                    b.ToTable("Habilidades", (string)null);

                    b.HasDiscriminator<string>("Discriminador").HasValue("Habilidade");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Itens.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Discriminador")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Itens", (string)null);

                    b.HasDiscriminator<string>("Discriminador").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Seres.Ser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AcoesPorTurno")
                        .HasColumnType("int");

                    b.Property<decimal>("BonusDeCritico")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Critico")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DanoBaseMaximo")
                        .HasColumnType("int");

                    b.Property<int>("DanoBaseMinimo")
                        .HasColumnType("int");

                    b.Property<decimal>("Esquiva")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("HpAtual")
                        .HasColumnType("int");

                    b.Property<int>("HpMaximo")
                        .HasColumnType("int");

                    b.Property<int>("Movimento")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Precisao")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Protecao")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Tamanho")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Velocidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seres", null, t =>
                        {
                            t.HasCheckConstraint("CK_Seres_DanoBase", "[DanoBaseMinimo] >= 0 AND [DanoBaseMaximo] >= 0 AND [DanoBaseMinimo] <= [DanoBaseMaximo]");

                            t.HasCheckConstraint("CK_Seres_HP", "[HpMaximo] >= 0 AND [HpAtual] >= 0 AND [HpAtual] <= [HpMaximo]");

                            t.HasCheckConstraint("CK_Seres_Nivel", "[Nivel] >= 0 AND [Nivel] <= 6");

                            t.HasCheckConstraint("CK_Seres_Percentuais", "[Critico] >= 0 AND [Critico] <= 100 AND [BonusDeCritico] >= 0 AND [BonusDeCritico] <= 100 AND [Protecao] >= 0 AND [Protecao] <= 100");

                            t.HasCheckConstraint("CK_Seres_Resistencias", "[Resistencias_Atordoamento] >= 0 AND [Resistencias_Atordoamento] <= 100 AND [Resistencias_Sangramento] >= 0 AND [Resistencias_Sangramento] <= 100 AND [Resistencias_Envenenamento] >= 0 AND [Resistencias_Envenenamento] <= 100 AND [Resistencias_Debuff] >= 0 AND [Resistencias_Debuff] <= 100 AND [Resistencias_Movimento] >= 0 AND [Resistencias_Movimento] <= 100");

                            t.HasCheckConstraint("CK_Seres_Tamanho", "[Tamanho] >= 0 AND [Tamanho] <= 4");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Habilidades.HabilidadeDeAcampamento", b =>
                {
                    b.HasBaseType("DarkestDungeon.Domain.Habilidades.Habilidade");

                    b.Property<string>("Alvo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CustoDeDescanso")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Acampamento");
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Habilidades.HabilidadeDeCombate", b =>
                {
                    b.HasBaseType("DarkestDungeon.Domain.Habilidades.Habilidade");

                    b.Property<bool>("AlvoEmArea")
                        .HasColumnType("bit");

                    b.Property<decimal>("ModificadorAcerto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ModificadorCritico")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ModificadorDano")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Combate");
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Habilidades.HabilidadeDeInimigo", b =>
                {
                    b.HasBaseType("DarkestDungeon.Domain.Habilidades.Habilidade");

                    b.Property<decimal?>("ChanceDeExecucao")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("CondicaoDeAparecer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasDiscriminator().HasValue("Inimigo");
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Itens.Acessorio", b =>
                {
                    b.HasBaseType("DarkestDungeon.Domain.Itens.Item");

                    b.Property<string>("ClasseExclusiva")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("ConjuntoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Raridade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasDiscriminator().HasValue("Acessorio");
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Itens.Arma", b =>
                {
                    b.HasBaseType("DarkestDungeon.Domain.Itens.Item");

                    b.Property<string>("ClasseElegivel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.ToTable("Itens", t =>
                        {
                            t.Property("ClasseElegivel")
                                .HasColumnName("Arma_ClasseElegivel");
                        });

                    b.HasDiscriminator().HasValue("Arma");
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Itens.Armadura", b =>
                {
                    b.HasBaseType("DarkestDungeon.Domain.Itens.Item");

                    b.Property<string>("ClasseElegivel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasDiscriminator().HasValue("Armadura");
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Seres.Inimigo", b =>
                {
                    b.HasBaseType("DarkestDungeon.Domain.Seres.Ser");

                    b.Property<string>("TipoDeInimigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.ToTable("Inimigos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Seres_DanoBase", "[DanoBaseMinimo] >= 0 AND [DanoBaseMaximo] >= 0 AND [DanoBaseMinimo] <= [DanoBaseMaximo]");

                            t.HasCheckConstraint("CK_Seres_HP", "[HpMaximo] >= 0 AND [HpAtual] >= 0 AND [HpAtual] <= [HpMaximo]");

                            t.HasCheckConstraint("CK_Seres_Nivel", "[Nivel] >= 0 AND [Nivel] <= 6");

                            t.HasCheckConstraint("CK_Seres_Percentuais", "[Critico] >= 0 AND [Critico] <= 100 AND [BonusDeCritico] >= 0 AND [BonusDeCritico] <= 100 AND [Protecao] >= 0 AND [Protecao] <= 100");

                            t.HasCheckConstraint("CK_Seres_Resistencias", "[Resistencias_Atordoamento] >= 0 AND [Resistencias_Atordoamento] <= 100 AND [Resistencias_Sangramento] >= 0 AND [Resistencias_Sangramento] <= 100 AND [Resistencias_Envenenamento] >= 0 AND [Resistencias_Envenenamento] <= 100 AND [Resistencias_Debuff] >= 0 AND [Resistencias_Debuff] <= 100 AND [Resistencias_Movimento] >= 0 AND [Resistencias_Movimento] <= 100");

                            t.HasCheckConstraint("CK_Seres_Tamanho", "[Tamanho] >= 0 AND [Tamanho] <= 4");
                        });
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Seres.Personagem", b =>
                {
                    b.HasBaseType("DarkestDungeon.Domain.Seres.Ser");

                    b.Property<Guid?>("AcessorioEquipado1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcessorioEquipado2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aflicao")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid?>("ArmaEquipadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArmaduraEquipadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChanceDeVirtude")
                        .HasColumnType("int");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("EstadoPortasDaMorte")
                        .HasColumnType("bit");

                    b.Property<bool>("RecuperouAtaqueCardiaco")
                        .HasColumnType("bit");

                    b.Property<bool>("RecuperouPortasDaMorte")
                        .HasColumnType("bit");

                    b.Property<int>("Stress")
                        .HasColumnType("int");

                    b.Property<string>("Virtude")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.ToTable("Personagens", null, t =>
                        {
                            t.HasCheckConstraint("CK_Seres_DanoBase", "[DanoBaseMinimo] >= 0 AND [DanoBaseMaximo] >= 0 AND [DanoBaseMinimo] <= [DanoBaseMaximo]");

                            t.HasCheckConstraint("CK_Seres_HP", "[HpMaximo] >= 0 AND [HpAtual] >= 0 AND [HpAtual] <= [HpMaximo]");

                            t.HasCheckConstraint("CK_Seres_Nivel", "[Nivel] >= 0 AND [Nivel] <= 6");

                            t.HasCheckConstraint("CK_Seres_Percentuais", "[Critico] >= 0 AND [Critico] <= 100 AND [BonusDeCritico] >= 0 AND [BonusDeCritico] <= 100 AND [Protecao] >= 0 AND [Protecao] <= 100");

                            t.HasCheckConstraint("CK_Seres_Resistencias", "[Resistencias_Atordoamento] >= 0 AND [Resistencias_Atordoamento] <= 100 AND [Resistencias_Sangramento] >= 0 AND [Resistencias_Sangramento] <= 100 AND [Resistencias_Envenenamento] >= 0 AND [Resistencias_Envenenamento] <= 100 AND [Resistencias_Debuff] >= 0 AND [Resistencias_Debuff] <= 100 AND [Resistencias_Movimento] >= 0 AND [Resistencias_Movimento] <= 100");

                            t.HasCheckConstraint("CK_Seres_Tamanho", "[Tamanho] >= 0 AND [Tamanho] <= 4");

                            t.HasCheckConstraint("CK_Personagens_ChanceVirtude", "[ChanceDeVirtude] >= 0 AND [ChanceDeVirtude] <= 100");

                            t.HasCheckConstraint("CK_Personagens_Stress", "[Stress] >= 0 AND [Stress] <= 200");
                        });
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Classes.Classe", b =>
                {
                    b.OwnsOne("DarkestDungeon.Domain.Classes.ResistenciasDeClasse", "ResistenciasBase", b1 =>
                        {
                            b1.Property<Guid>("ClasseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Armadilha")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("Atordoamento")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("Debuff")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("Doenca")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("Envenenamento")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("GolpeMortal")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("Movimento")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("Sangramento")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.HasKey("ClasseId");

                            b1.ToTable("Classes");

                            b1.WithOwner()
                                .HasForeignKey("ClasseId");
                        });

                    b.Navigation("ResistenciasBase")
                        .IsRequired();
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Classes.ClasseHabilidade", b =>
                {
                    b.HasOne("DarkestDungeon.Domain.Classes.Classe", null)
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DarkestDungeon.Domain.Habilidades.Habilidade", null)
                        .WithMany()
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Seres.Ser", b =>
                {
                    b.OwnsOne("DarkestDungeon.Domain.Seres.Resistencias", "Resistencias", b1 =>
                        {
                            b1.Property<Guid>("SerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Atordoamento")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("Debuff")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("Envenenamento")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("Movimento")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("Sangramento")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.HasKey("SerId");

                            b1.ToTable("Seres");

                            b1.WithOwner()
                                .HasForeignKey("SerId");
                        });

                    b.Navigation("Resistencias")
                        .IsRequired();
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Habilidades.HabilidadeDeAcampamento", b =>
                {
                    b.OwnsMany("DarkestDungeon.Domain.Habilidades.EfeitoDeHabilidade", "Efeitos", b1 =>
                        {
                            b1.Property<Guid>("HabilidadeDeAcampamentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Alvo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal>("ChanceBase")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<int?>("DuracaoEmRodadas")
                                .HasColumnType("int");

                            b1.Property<string>("NomeDoEfeito")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("Unidade")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)");

                            b1.HasKey("HabilidadeDeAcampamentoId", "Id");

                            b1.ToTable("EfeitosHabilidadeAcampamento", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("HabilidadeDeAcampamentoId");
                        });

                    b.OwnsOne("DarkestDungeon.Domain.Habilidades.LimitePorUso", "LimitePorUso", b1 =>
                        {
                            b1.Property<Guid>("HabilidadeDeAcampamentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Escopo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<int>("MaximoUsos")
                                .HasColumnType("int");

                            b1.HasKey("HabilidadeDeAcampamentoId");

                            b1.ToTable("Habilidades");

                            b1.WithOwner()
                                .HasForeignKey("HabilidadeDeAcampamentoId");
                        });

                    b.Navigation("Efeitos");

                    b.Navigation("LimitePorUso");
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Habilidades.HabilidadeDeCombate", b =>
                {
                    b.OwnsMany("DarkestDungeon.Domain.Habilidades.EfeitoDeHabilidade", "Efeitos", b1 =>
                        {
                            b1.Property<Guid>("HabilidadeDeCombateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Alvo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal>("ChanceBase")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<int?>("DuracaoEmRodadas")
                                .HasColumnType("int");

                            b1.Property<string>("NomeDoEfeito")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("Unidade")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)");

                            b1.HasKey("HabilidadeDeCombateId", "Id");

                            b1.ToTable("EfeitosHabilidadeCombate", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("HabilidadeDeCombateId");
                        });

                    b.OwnsOne("DarkestDungeon.Domain.Habilidades.LimitePorUso", "LimitePorUso", b1 =>
                        {
                            b1.Property<Guid>("HabilidadeDeCombateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Escopo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<int>("MaximoUsos")
                                .HasColumnType("int");

                            b1.HasKey("HabilidadeDeCombateId");

                            b1.ToTable("Habilidades", t =>
                                {
                                    t.Property("Escopo")
                                        .HasColumnName("LimitePorUso_Escopo1");

                                    t.Property("MaximoUsos")
                                        .HasColumnName("LimitePorUso_MaximoUsos1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("HabilidadeDeCombateId");
                        });

                    b.Navigation("Efeitos");

                    b.Navigation("LimitePorUso");
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Habilidades.HabilidadeDeInimigo", b =>
                {
                    b.OwnsMany("DarkestDungeon.Domain.Habilidades.EfeitoDeHabilidade", "Efeitos", b1 =>
                        {
                            b1.Property<Guid>("HabilidadeDeInimigoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Alvo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal>("ChanceBase")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<int?>("DuracaoEmRodadas")
                                .HasColumnType("int");

                            b1.Property<string>("NomeDoEfeito")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("Unidade")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)");

                            b1.HasKey("HabilidadeDeInimigoId", "Id");

                            b1.ToTable("EfeitosHabilidadeInimigo", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("HabilidadeDeInimigoId");
                        });

                    b.Navigation("Efeitos");
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Itens.Acessorio", b =>
                {
                    b.OwnsMany("DarkestDungeon.Domain.Itens.EfeitoDeAcessorio", "Efeitos", b1 =>
                        {
                            b1.Property<Guid>("AcessorioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)");

                            b1.Property<string>("Sinal")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Unidade")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)");

                            b1.HasKey("AcessorioId", "Id");

                            b1.ToTable("EfeitosAcessorio", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AcessorioId");
                        });

                    b.Navigation("Efeitos");
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Itens.Arma", b =>
                {
                    b.OwnsMany("DarkestDungeon.Domain.Itens.NivelDeArma", "Niveis", b1 =>
                        {
                            b1.Property<Guid>("ArmaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Critico")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<int>("DanoMaximo")
                                .HasColumnType("int");

                            b1.Property<int>("DanoMinimo")
                                .HasColumnType("int");

                            b1.Property<int>("Nivel")
                                .HasColumnType("int");

                            b1.Property<int>("Velocidade")
                                .HasColumnType("int");

                            b1.HasKey("ArmaId", "Id");

                            b1.ToTable("NiveisArma", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ArmaId");
                        });

                    b.Navigation("Niveis");
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Itens.Armadura", b =>
                {
                    b.OwnsMany("DarkestDungeon.Domain.Itens.NivelDeArmadura", "Niveis", b1 =>
                        {
                            b1.Property<Guid>("ArmaduraId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Esquiva")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<int>("HpAdicional")
                                .HasColumnType("int");

                            b1.Property<int>("Nivel")
                                .HasColumnType("int");

                            b1.HasKey("ArmaduraId", "Id");

                            b1.ToTable("NiveisArmadura", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ArmaduraId");
                        });

                    b.Navigation("Niveis");
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Seres.Inimigo", b =>
                {
                    b.HasOne("DarkestDungeon.Domain.Seres.Ser", null)
                        .WithOne()
                        .HasForeignKey("DarkestDungeon.Domain.Seres.Inimigo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarkestDungeon.Domain.Seres.Personagem", b =>
                {
                    b.HasOne("DarkestDungeon.Domain.Seres.Ser", null)
                        .WithOne()
                        .HasForeignKey("DarkestDungeon.Domain.Seres.Personagem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("DarkestDungeon.Domain.Personagens.HabilidadeDePersonagem", "Habilidades", b1 =>
                        {
                            b1.Property<Guid>("PersonagemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("Equipada")
                                .HasColumnType("bit");

                            b1.Property<Guid>("HabilidadeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Habilitada")
                                .HasColumnType("bit");

                            b1.Property<bool>("Treinada")
                                .HasColumnType("bit");

                            b1.HasKey("PersonagemId", "Id");

                            b1.ToTable("HabilidadesDePersonagem", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PersonagemId");
                        });

                    b.OwnsOne("DarkestDungeon.Domain.Personagens.ResistenciasExtrasDePersonagem", "ResistenciasExtras", b1 =>
                        {
                            b1.Property<Guid>("PersonagemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Armadilha")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("Doenca")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal>("GolpeMortal")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.HasKey("PersonagemId");

                            b1.ToTable("Personagens");

                            b1.WithOwner()
                                .HasForeignKey("PersonagemId");
                        });

                    b.Navigation("Habilidades");

                    b.Navigation("ResistenciasExtras")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
